---
title: "congeniality"
author: "Gustav Idun Sloth"
date: "2026-01-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lme4)
library(lmerTest)
library(emmeans)
library(performance)
library(DHARMa)

my_theme <- theme_bw() +
  theme(
    plot.title  = element_text(family = "Helvetica", face = "bold"),
    axis.title  = element_text(family = "Helvetica"),
    axis.text   = element_text(family = "Helvetica"),
    legend.text = element_text(family = "Helvetica"),
    legend.title= element_text(family = "Helvetica"),
    strip.text  = element_text(family = "Helvetica")
  )
```


```{r data}
df_vid <- read_csv("../data/puppets/processed/27-12/vid_long.csv")
```
```{r test}

df_plot <- filter(df_vid, cond_group == "random", utility == TRUE)
df_plot.length

```

```{r proportion}
library(scales)

df_plot <- filter(df_vid, cond_group == "random", utility == TRUE)

df_vid$slant_start_label <- factor(
  df_vid$slant_start_label,
  levels = c("Far left","Left","Center","Right","Far right")
)

df_plot <- df_plot %>%
  mutate(
    rec_slants = as.numeric(recs_slant),
    rec_label = cut(
      recs_slant,
      breaks = c(-1, -0.6, -0.2, 0.2, 0.6, 1.0000001),
      right  = FALSE,
      labels = c("Far left", "Left", "Center", "Right", "Far right")
    ),
    rec_label = factor(rec_label, levels = c("Far left","Left","Center","Right","Far right"))
  ) %>%
  filter(!is.na(slant_start_label), !is.na(rec_label)) %>%
  count(slant_start_label, rec_label, name = "n") %>%
  group_by(slant_start_label) %>%
  mutate(prop = n / sum(n)) %>%
  ungroup()

ggplot(df_plot, aes(x = slant_start_label, y = prop, fill = rec_label)) +
  geom_col(width = 0.9) +
  geom_text(
    aes(label = percent(prop, accuracy = 0.1)),
    position = position_stack(vjust = 0.5),
    size = 3,
    color = "white"
  ) +
  scale_y_continuous(labels = percent_format(), limits = c(0, 1)) +
  scale_fill_manual(values = c(
    "Far left"  = "blue",
    "Left"       = "lightblue",
    "Center"     = "purple",
    "Right"      = "salmon",
    "Far right" = "red"
  )) +
  labs(x = NULL, y = "Proportion", fill = NULL) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    panel.grid.major.x = element_blank(),
    panel.grid.minor = element_blank(),
    aspect.ratio = 1
  )
```


